language: node_js
node_js:
  - 10

#指定分支，只有指定分支的提交才会运行脚本
branches:

cache:
  directories:
    - node_modules
install:
  - yarn install
#项目执行命令
before_script:
  - yarn run bootstrap
script:
   # 执行测试的命令
  - yarn build
  - yarn run coverage
  - codecov
after_success:
  - CODECOV_TOKEN=$CODECOV_TOKEN
  - bash <(curl -s https://codecov.io/bash)
