language: node_js
node_js:
  - 10

#指定分支，只有指定分支的提交才会运行脚本
branches:

cache:
  directories:
    - node_modules
    - packages/combine/node_modules
    - packages/css/node_modules
    - packages/dict/node_modules
    - packages/indexDB/node_modules
    - packages/libs-example/node_modules
    - packages/listener/node_modules
    - packages/math/node_modules
    - packages/object-utils/node_modules
    - packages/ramada/node_modules
    - packages/theme-config/node_modules
    - packages/theme-core/node_modules
    - packages/theme-css-hoc/node_modules
    - packages/theme-hoc/node_modules
    - packages/theme-utils/node_modules
    - packages/unique/node_modules
install:
  - yarn install
#项目执行命令
before_script:
  - yarn build
script:
  # 执行测试的命令
  - yarn run coverage
  - codecov
after_success:
  - CODECOV_TOKEN=$CODECOV_TOKEN
  - bash <(curl -s https://codecov.io/bash)
